In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('D:\\Documents\\ML\\shell_dataset\\dataset\\train\\train\\train.csv')

In [2]:
df.shape

(527040, 17)

In [3]:
df = df.rename(columns={'Global CMP22 (vent/cor) [W/m^2]':'CMP22', 'Direct sNIP [W/m^2]':'sNIP', 'Azimuth Angle [degrees]':'Angle', 'Tower Dry Bulb Temp [deg C]':'dryBulbTemp', 'Tower Wet Bulb Temp [deg C]':'wetBulbTemp', 'Tower Dew Point Temp [deg C]':'dewPtTemp', 'Tower RH [%]':'RH', 'Total Cloud Cover [%]':'TCC', 'Peak Wind Speed @ 6ft [m/s]':'windSpeed', 'Station Pressure [mBar]':'pressure', 'Precipitation (Accumulated) [mm]':'rain', 'Snow Depth [cm]':'snowDepth', 'Albedo (CMP11)':'Albedo','Avg Wind Direction @ 6ft [deg from N]':'windDirection'})

In [4]:
df.columns

Index(['DATE (MM/DD)', 'MST', 'CMP22', 'sNIP', 'Angle', 'dryBulbTemp',
       'wetBulbTemp', 'dewPtTemp', 'RH', 'TCC', 'windSpeed', 'windDirection',
       'pressure', 'rain', 'snowDepth', 'Moisture', 'Albedo'],
      dtype='object')

In [18]:
new_columnName = ['DATE (MM/DD)', 'MST', 'CMP22', 'sNIP', 'Angle', 'dryBulbTemp',
       'wetBulbTemp', 'dewPtTemp', 'RH', 'windSpeed', 'windDirection',
       'pressure', 'rain', 'snowDepth', 'Moisture', 'Albedo', 'TCC']
df = df.reindex(columns=new_columnName)
df.columns

Index(['DATE (MM/DD)', 'MST', 'CMP22', 'sNIP', 'Angle', 'dryBulbTemp',
       'wetBulbTemp', 'dewPtTemp', 'RH', 'windSpeed', 'windDirection',
       'pressure', 'rain', 'snowDepth', 'Moisture', 'Albedo', 'TCC'],
      dtype='object')

In [25]:
nightData = df[df.TCC<=-1]

In [26]:
nightData.shape

(276309, 17)

In [15]:
df.columns

Index(['DATE (MM/DD)', 'MST', 'CMP22', 'sNIP', 'Angle', 'dryBulbTemp',
       'wetBulbTemp', 'dewPtTemp', 'RH', 'TCC', 'windSpeed', 'windDirection',
       'pressure', 'rain', 'snowDepth', 'Moisture', 'Albedo'],
      dtype='object')

In [30]:
df[df.TCC > -1].count()

DATE (MM/DD)     250731
MST              250731
CMP22            250731
sNIP             250731
Angle            250731
dryBulbTemp      250731
wetBulbTemp      250731
dewPtTemp        250731
RH               250731
windSpeed        250731
windDirection    250731
pressure         250731
rain             250731
snowDepth        250731
Moisture         250731
Albedo           250731
TCC              250731
dtype: int64

In [31]:
df = df[df.TCC > -1]

In [32]:
df.shape

(250731, 17)

In [33]:
df.head(5)

,DATE (MM/DD),MST,CMP22,sNIP,Angle,dryBulbTemp,wetBulbTemp,dewPtTemp,RH,windSpeed,windDirection,pressure,rain,snowDepth,Moisture,Albedo,TCC
467,1/1,07:47,14.4935,0.079127,123.84491,6.933,1.403,-5.597,38.24,0.7,210.3,802.042,0.0,0.032,0.0,0.1951,6
468,1/1,07:48,16.5178,-0.034618,124.01096,6.793,1.294,-5.606,38.58,0.7,232.2,801.948,0.0,0.029,0.0,0.1867,8
469,1/1,07:49,18.6171,-0.153309,124.17734,6.674,1.260,-5.540,39.12,1.7,263.9,801.940,0.0,0.173,0.0,0.1783,10
470,1/1,07:50,20.5986,-0.143419,124.34405,6.646,1.306,-5.494,39.35,2.2,277.5,801.927,0.0,0.144,0.0,0.1758,13
471,1/1,07:51,22.4362,-0.079128,124.51110,6.676,1.316,-5.384,39.64,2.2,233.4,801.829,0.0,0.355,0.0,0.1765,15

In [39]:
df['time'] = df.apply(lambda x: (x['MST'].split(':')[0]*60)+(x['MST'].split(':')[1]), axis=1)
df.columns

Index(['DATE (MM/DD)', 'MST', 'CMP22', 'sNIP', 'Angle', 'dryBulbTemp',
       'wetBulbTemp', 'dewPtTemp', 'RH', 'windSpeed', 'windDirection',
       'pressure', 'rain', 'snowDepth', 'Moisture', 'Albedo', 'TCC', 'time'],
      dtype='object')

In [72]:
x = df.MST.head(1)
y = int(str(x).split(" ")[4].split('\n')[0].split(':')[0])*60+int(str(x).split(" ")[4].split('\n')[0].split(':')[1])
y

467

In [89]:
x

467    07:47
Name: MST, dtype: object

In [94]:
s = df['MST']
arr=[]
for index, val in s.items():
    arr.append((int(str(val).split(':')[0])*60) + (int(str(val).split(':')[1])))
df2 = df.assign(time = arr)

df2.shape

(250731, 18)

In [95]:
df2.head(2)

,DATE (MM/DD),MST,CMP22,sNIP,Angle,dryBulbTemp,wetBulbTemp,dewPtTemp,RH,windSpeed,windDirection,pressure,rain,snowDepth,Moisture,Albedo,TCC,time
467,1/1,07:47,14.4935,0.079127,123.84491,6.933,1.403,-5.597,38.24,0.7,210.3,802.042,0.0,0.032,0.0,0.1951,6,467
468,1/1,07:48,16.5178,-0.034618,124.01096,6.793,1.294,-5.606,38.58,0.7,232.2,801.948,0.0,0.029,0.0,0.1867,8,468

In [97]:
new_columnName = ['DATE (MM/DD)', 'MST', 'time', 'CMP22', 'sNIP', 'Angle', 'dryBulbTemp',
       'wetBulbTemp', 'dewPtTemp', 'RH', 'windSpeed', 'windDirection',
       'pressure', 'rain', 'snowDepth', 'Moisture', 'Albedo', 'TCC']
df2 = df2.reindex(columns=new_columnName)
df2.head(2)

,DATE (MM/DD),MST,time,CMP22,sNIP,Angle,dryBulbTemp,wetBulbTemp,dewPtTemp,RH,windSpeed,windDirection,pressure,rain,snowDepth,Moisture,Albedo,TCC
467,1/1,07:47,467,14.4935,0.079127,123.84491,6.933,1.403,-5.597,38.24,0.7,210.3,802.042,0.0,0.032,0.0,0.1951,6
468,1/1,07:48,468,16.5178,-0.034618,124.01096,6.793,1.294,-5.606,38.58,0.7,232.2,801.948,0.0,0.029,0.0,0.1867,8

In [101]:
new_columnName = ['DATE (MM/DD)', 'MST', 'time', 'CMP22', 'sNIP', 'Angle', 'dryBulbTemp',
       'wetBulbTemp', 'dewPtTemp', 'RH', 'windSpeed', 'windDirection',
       'pressure', 'rain', 'snowDepth', 'Moisture', 'Albedo', 'TCC', 'TCC_30min', 'TCC_60min','TCC_90min','TCC_120min']
df2 = df2.reindex(columns=new_columnName)
df2.tail(3)

,DATE (MM/DD),MST,time,CMP22,sNIP,Angle,dryBulbTemp,wetBulbTemp,dewPtTemp,RH,...,pressure,rain,snowDepth,Moisture,Albedo,TCC,TCC_30min,TCC_60min,TCC_90min,TCC_120min
526583,12/31,16:23,983,15.6230,-0.197509,236.45711,2.235,-1.773,-7.973,43.24,...,812.664,0.0,2.696,0.0,0.2470,8,NaN,NaN,NaN,NaN
526584,12/31,16:24,984,14.5605,-0.202446,236.62235,2.245,-1.683,-7.683,44.32,...,812.675,0.0,2.654,0.0,0.2462,7,NaN,NaN,NaN,NaN
526585,12/31,16:25,985,13.7140,-0.222196,236.78727,2.226,-1.681,-7.581,44.78,...,812.695,0.0,2.653,0.0,0.2438,7,NaN,NaN,NaN,NaN

In [109]:
df3=df2
df3.head(5)

,DATE (MM/DD),MST,time,CMP22,sNIP,Angle,dryBulbTemp,wetBulbTemp,dewPtTemp,RH,...,pressure,rain,snowDepth,Moisture,Albedo,TCC,TCC_30min,TCC_60min,TCC_90min,TCC_120min
467,1/1,07:47,467,14.4935,0.079127,123.84491,6.933,1.403,-5.597,38.24,...,802.042,0.0,0.032,0.0,0.1951,6,NaN,NaN,NaN,NaN
468,1/1,07:48,468,16.5178,-0.034618,124.01096,6.793,1.294,-5.606,38.58,...,801.948,0.0,0.029,0.0,0.1867,8,NaN,NaN,NaN,NaN
469,1/1,07:49,469,18.6171,-0.153309,124.17734,6.674,1.260,-5.540,39.12,...,801.940,0.0,0.173,0.0,0.1783,10,NaN,NaN,NaN,NaN
470,1/1,07:50,470,20.5986,-0.143419,124.34405,6.646,1.306,-5.494,39.35,...,801.927,0.0,0.144,0.0,0.1758,13,NaN,NaN,NaN,NaN
471,1/1,07:51,471,22.4362,-0.079128,124.51110,6.676,1.316,-5.384,39.64,...,801.829,0.0,0.355,0.0,0.1765,15,NaN,NaN,NaN,NaN

In [116]:
df3.loc[467, 'TCC_30min'] = df3.loc[467+30,'TCC']

In [117]:
df3.head(5)

,DATE (MM/DD),MST,time,CMP22,sNIP,Angle,dryBulbTemp,wetBulbTemp,dewPtTemp,RH,...,pressure,rain,snowDepth,Moisture,Albedo,TCC,TCC_30min,TCC_60min,TCC_90min,TCC_120min
467,1/1,07:47,467,14.4935,0.079127,123.84491,6.933,1.403,-5.597,38.24,...,802.042,0.0,0.032,0.0,0.1951,6,20.0,NaN,NaN,NaN
468,1/1,07:48,468,16.5178,-0.034618,124.01096,6.793,1.294,-5.606,38.58,...,801.948,0.0,0.029,0.0,0.1867,8,NaN,NaN,NaN,NaN
469,1/1,07:49,469,18.6171,-0.153309,124.17734,6.674,1.260,-5.540,39.12,...,801.940,0.0,0.173,0.0,0.1783,10,NaN,NaN,NaN,NaN
470,1/1,07:50,470,20.5986,-0.143419,124.34405,6.646,1.306,-5.494,39.35,...,801.927,0.0,0.144,0.0,0.1758,13,NaN,NaN,NaN,NaN
471,1/1,07:51,471,22.4362,-0.079128,124.51110,6.676,1.316,-5.384,39.64,...,801.829,0.0,0.355,0.0,0.1765,15,NaN,NaN,NaN,NaN

In [120]:
for index, row in df.iterrows():
    try:
        df3.loc[index, 'TCC_30min'] = df3.loc[index+30,'TCC']
        df3.loc[index, 'TCC_60min'] = df3.loc[index+60,'TCC']
        df3.loc[index, 'TCC_90min'] = df3.loc[index+90,'TCC']
        df3.loc[index, 'TCC_120min'] = df3.loc[index+120,'TCC']
    except KeyError:
        pass

In [134]:
df3.head(2)

,DATE (MM/DD),MST,time,CMP22,sNIP,Angle,dryBulbTemp,wetBulbTemp,dewPtTemp,RH,...,pressure,rain,snowDepth,Moisture,Albedo,TCC,TCC_30min,TCC_60min,TCC_90min,TCC_120min
467,1/1,07:47,467,14.4935,0.079127,123.84491,6.933,1.403,-5.597,38.24,...,802.042,0.0,0.032,0.0,0.1951,6,20.0,13.0,17.0,46.0
468,1/1,07:48,468,16.5178,-0.034618,124.01096,6.793,1.294,-5.606,38.58,...,801.948,0.0,0.029,0.0,0.1867,8,19.0,15.0,14.0,52.0

In [135]:
df3.loc[860:900]

,DATE (MM/DD),MST,time,CMP22,sNIP,Angle,dryBulbTemp,wetBulbTemp,dewPtTemp,RH,...,pressure,rain,snowDepth,Moisture,Albedo,TCC,TCC_30min,TCC_60min,TCC_90min,TCC_120min
860,1/1,14:20,860,182.820,51.250,213.10140,9.99,2.332,-7.868,25.52,...,801.182,0.0,0.350,0.0,0.1826,65,5.0,12.0,7.0,1.0
861,1/1,14:21,861,278.063,348.522,213.31870,10.02,2.295,-7.805,25.61,...,801.240,0.0,0.364,0.0,0.2016,64,6.0,12.0,8.0,2.0
862,1/1,14:22,862,469.131,914.875,213.53552,10.18,2.509,-7.391,26.27,...,801.308,0.0,0.444,0.0,0.2269,64,7.0,9.0,7.0,1.0
863,1/1,14:23,863,455.829,909.476,213.75186,10.54,2.702,-7.398,25.63,...,801.314,0.0,0.453,0.0,0.2265,63,8.0,9.0,2.0,2.0
864,1/1,14:24,864,444.202,910.140,213.96773,10.85,2.747,-7.753,24.34,...,801.380,0.0,0.468,0.0,0.2273,59,9.0,9.0,5.0,2.0
865,1/1,14:25,865,431.434,910.312,214.18312,11.08,2.958,-7.442,24.63,...,801.431,0.0,0.548,0.0,0.2281,56,9.0,10.0,6.0,2.0
866,1/1,14:26,866,417.150,909.185,214.39804,11.36,3.196,-7.104,24.90,...,801.386,0.0,0.504,0.0,0.2293,54,9.0,10.0,3.0,NaN
867,1/1,14:27,867,402.741,908.088,214.61247,11.63,3.273,-7.127,24.41,...,801.288,0.0,0.504,0.0,0.2309,50,8.0,9.0,4.0,NaN
868,1/1,14:28,868,389.338,908.048,214.82644,11.81,3.495,-6.905,24.59,...,801.234,0.0,0.581,0.0,0.2326,45,6.0,8.0,2.0,NaN
869,1/1,14:29,869,378.266,907.152,215.03992,12.00,3.614,-6.686,24.75,...,801.328,0.0,0.343,0.0,0.2341,39,5.0,9.0,5.0,NaN
870,1/1,14:30,870,369.103,905.812,215.25293,12.08,3.546,-7.154,23.64,...,801.440,0.0,0.144,0.0,0.2353,34,4.0,7.0,2.0,NaN
871,1/1,14:31,871,361.685,904.543,215.46546,11.98,3.416,-7.484,23.12,...,801.490,0.0,0.149,0.0,0.2356,32,4.0,6.0,3.0,NaN
872,1/1,14:32,872,354.681,902.524,215.67751,11.85,3.342,-7.558,23.17,...,801.495,0.0,0.091,0.0,0.2352,30,4.0,7.0,3.0,NaN
873,1/1,14:33,873,348.293,901.964,215.88908,11.85,3.350,-7.250,23.80,...,801.473,0.0,0.270,0.0,0.2353,27,4.0,8.0,3.0,NaN
874,1/1,14:34,874,342.154,899.768,216.10018,11.88,3.497,-7.003,24.27,...,801.452,0.0,0.259,0.0,0.2356,24,3.0,8.0,3.0,NaN
875,1/1,14:35,875,337.064,898.784,216.31081,11.80,3.482,-6.718,25.01,...,801.467,0.0,0.312,0.0,0.2356,22,3.0,5.0,2.0,NaN
876,1/1,14:36,876,332.642,898.260,216.52095,11.78,3.350,-7.250,23.91,...,801.536,0.0,0.265,0.0,0.2363,20,4.0,6.0,3.0,NaN
877,1/1,14:37,877,327.985,894.402,216.73062,11.51,3.148,-7.552,23.71,...,801.634,0.0,0.276,0.0,0.2372,18,5.0,5.0,3.0,NaN
878,1/1,14:38,878,324.188,891.182,216.93982,11.10,2.922,-7.478,24.52,...,801.664,0.0,0.208,0.0,0.2374,17,6.0,6.0,3.0,NaN
879,1/1,14:39,879,321.314,890.587,217.14853,10.83,2.879,-7.221,25.53,...,801.598,0.0,0.259,0.0,0.2364,17,7.0,5.0,2.0,NaN
880,1/1,14:40,880,318.094,888.494,217.35678,10.70,2.847,-7.053,26.13,...,801.609,0.0,0.280,0.0,0.2360,16,7.0,5.0,2.0,NaN
881,1/1,14:41,881,314.151,884.206,217.56454,10.56,2.853,-7.047,26.39,...,801.640,0.0,0.255,0.0,0.2357,15,9.0,5.0,2.0,NaN
882,1/1,14:42,882,310.894,881.860,217.77184,10.35,2.613,-7.287,26.21,...,801.553,0.0,0.227,0.0,0.2369,13,10.0,5.0,2.0,NaN
883,1/1,14:43,883,306.976,876.531,217.97865,10.02,2.450,-7.250,26.88,...,801.479,0.0,0.248,0.0,0.2379,12,11.0,7.0,2.0,NaN
884,1/1,14:44,884,304.511,875.495,218.18500,9.69,2.323,-7.377,27.18,...,801.539,0.0,0.283,0.0,0.2397,11,12.0,8.0,1.0,NaN
885,1/1,14:45,885,301.891,873.133,218.39087,9.44,2.181,-7.319,27.78,...,801.531,0.0,0.321,0.0,0.2396,10,13.0,8.0,1.0,NaN
886,1/1,14:46,886,299.022,870.094,218.59627,9.29,2.106,-7.194,28.37,...,801.550,0.0,0.309,0.0,0.2391,10,13.0,9.0,1.0,NaN
887,1/1,14:47,887,295.881,867.826,218.80119,9.22,2.116,-7.184,28.53,...,801.586,0.0,0.326,0.0,0.2394,8,13.0,9.0,1.0,NaN
888,1/1,14:48,888,293.011,866.632,219.00565,9.09,1.983,-7.317,28.45,...,801.584,0.0,0.356,0.0,0.2417,7,12.0,8.0,1.0,NaN
889,1/1,14:49,889,290.091,864.411,219.20963,8.96,1.833,-7.567,28.08,...,801.542,0.0,0.395,0.0,0.2423,7,11.0,8.0,1.0,NaN
890,1/1,14:50,890,286.971,860.357,219.41315,8.84,1.758,-7.742,27.88,...,801.565,0.0,0.398,0.0,0.2438,5,12.0,7.0,1.0,NaN
891,1/1,14:51,891,284.360,857.856,219.61619,8.73,1.638,-7.762,28.04,...,801.566,0.0,0.400,0.0,0.2454,6,12.0,8.0,2.0,NaN
892,1/1,14:52,892,282.073,855.121,219.81876,8.56,1.597,-7.703,28.51,...,801.605,0.0,0.453,0.0,0.2458,7,9.0,7.0,1.0,NaN
893,1/1,14:53,893,280.477,855.171,220.02087,8.49,1.622,-7.678,28.71,...,801.653,0.0,0.496,0.0,0.2457,8,9.0,2.0,2.0,NaN
894,1/1,14:54,894,278.743,854.277,220.22251,8.48,1.606,-7.594,28.94,...,801.737,0.0,0.458,0.0,0.2463,9,9.0,5.0,2.0,NaN
895,1/1,14:55,895,275.887,852.045,220.42368,8.47,1.620,-7.480,29.25,...,801.728,0.0,0.501,0.0,0.2457,9,10.0,6.0,2.0,NaN
896,1/1,14:56,896,272.137,847.295,220.62439,8.47,1.575,-7.725,28.63,...,801.729,0.0,0.499,0.0,0.2463,9,10.0,3.0,NaN,NaN
897,1/1,14:57,897,269.126,845.224,220.82463,8.48,1.622,-7.678,28.73,...,801.766,0.0,0.498,0.0,0.2467,8,9.0,4.0,NaN,NaN
898,1/1,14:58,898,265.409,839.966,221.02441,8.53,1.485,-8.015,27.80,...,801.803,0.0,0.477,0.0,0.2474,6,8.0,2.0,NaN,NaN
899,1/1,14:59,899,263.276,839.456,221.22372,8.54,1.427,-8.173,27.40,...,801.773,0.0,0.463,0.0,0.2482,5,9.0,5.0,NaN,NaN
900,1/1,15:00,900,260.576,838.131,221.42257,8.55,1.554,-7.946,27.93,...,801.822,0.0,0.492,0.0,0.2485,4,7.0,2.0,NaN,NaN

In [138]:
df3.shape

(250731, 22)

In [141]:
df4 = df3.dropna(subset=['TCC_30min', 'TCC_60min', 'TCC_90min', 'TCC_120min'], how='any')
df4.shape

(201627, 22)

In [142]:
df4.loc[860:900]

,DATE (MM/DD),MST,time,CMP22,sNIP,Angle,dryBulbTemp,wetBulbTemp,dewPtTemp,RH,...,pressure,rain,snowDepth,Moisture,Albedo,TCC,TCC_30min,TCC_60min,TCC_90min,TCC_120min
860,1/1,14:20,860,182.820,51.250,213.10140,9.99,2.332,-7.868,25.52,...,801.182,0.0,0.350,0.0,0.1826,65,5.0,12.0,7.0,1.0
861,1/1,14:21,861,278.063,348.522,213.31870,10.02,2.295,-7.805,25.61,...,801.240,0.0,0.364,0.0,0.2016,64,6.0,12.0,8.0,2.0
862,1/1,14:22,862,469.131,914.875,213.53552,10.18,2.509,-7.391,26.27,...,801.308,0.0,0.444,0.0,0.2269,64,7.0,9.0,7.0,1.0
863,1/1,14:23,863,455.829,909.476,213.75186,10.54,2.702,-7.398,25.63,...,801.314,0.0,0.453,0.0,0.2265,63,8.0,9.0,2.0,2.0
864,1/1,14:24,864,444.202,910.140,213.96773,10.85,2.747,-7.753,24.34,...,801.380,0.0,0.468,0.0,0.2273,59,9.0,9.0,5.0,2.0
865,1/1,14:25,865,431.434,910.312,214.18312,11.08,2.958,-7.442,24.63,...,801.431,0.0,0.548,0.0,0.2281,56,9.0,10.0,6.0,2.0

In [144]:
df5=df3
df5.head(2)
df5.shape

(250731, 22)

In [145]:
df5.fillna(-1)

,DATE (MM/DD),MST,time,CMP22,sNIP,Angle,dryBulbTemp,wetBulbTemp,dewPtTemp,RH,...,pressure,rain,snowDepth,Moisture,Albedo,TCC,TCC_30min,TCC_60min,TCC_90min,TCC_120min
467,1/1,07:47,467,14.4935,0.079127,123.84491,6.933,1.403,-5.597,38.24,...,802.042,0.0,0.032,0.0,0.1951,6,20.0,13.0,17.0,46.0
468,1/1,07:48,468,16.5178,-0.034618,124.01096,6.793,1.294,-5.606,38.58,...,801.948,0.0,0.029,0.0,0.1867,8,19.0,15.0,14.0,52.0
469,1/1,07:49,469,18.6171,-0.153309,124.17734,6.674,1.260,-5.540,39.12,...,801.940,0.0,0.173,0.0,0.1783,10,17.0,15.0,13.0,57.0
470,1/1,07:50,470,20.5986,-0.143419,124.34405,6.646,1.306,-5.494,39.35,...,801.927,0.0,0.144,0.0,0.1758,13,15.0,14.0,12.0,59.0
471,1/1,07:51,471,22.4362,-0.079128,124.51110,6.676,1.316,-5.384,39.64,...,801.829,0.0,0.355,0.0,0.1765,15,16.0,13.0,11.0,64.0
472,1/1,07:52,472,23.9323,0.034618,124.67847,6.928,1.497,-5.303,39.23,...,801.807,0.0,0.337,0.0,0.1787,19,15.0,12.0,10.0,66.0
473,1/1,07:53,473,24.9174,0.158256,124.84619,7.190,1.644,-5.156,39.02,...,801.842,0.0,0.407,0.0,0.1816,19,15.0,12.0,9.0,69.0
474,1/1,07:54,474,25.5693,0.365967,125.01424,7.642,1.943,-5.147,37.86,...,801.969,0.0,0.423,0.0,0.1810,21,15.0,15.0,9.0,71.0
475,1/1,07:55,475,25.8414,0.509386,125.18263,7.926,2.073,-5.027,37.52,...,802.025,0.0,0.220,0.0,0.2006,21,15.0,14.0,8.0,73.0
476,1/1,07:56,476,25.7414,0.519275,125.35136,8.010,2.140,-5.060,37.20,...,802.013,0.0,0.328,0.0,0.2051,22,14.0,15.0,8.0,73.0
477,1/1,07:57,477,25.6456,0.623130,125.52044,8.190,2.200,-5.100,36.62,...,801.985,0.0,0.321,0.0,0.2040,23,17.0,19.0,8.0,76.0
478,1/1,07:58,478,25.9762,0.741822,125.68987,8.410,2.272,-5.128,35.99,...,802.045,0.0,0.312,0.0,0.2083,22,17.0,20.0,10.0,77.0
479,1/1,07:59,479,26.9733,0.816008,125.85964,8.530,2.411,-5.089,35.82,...,802.085,0.0,0.262,0.0,0.2111,24,17.0,23.0,12.0,78.0
480,1/1,08:00,480,28.8356,0.825900,126.02976,8.660,2.480,-5.120,35.41,...,802.093,0.0,0.257,0.0,0.2118,25,18.0,25.0,13.0,81.0
481,1/1,08:01,481,31.5678,0.806120,126.20024,8.750,2.498,-5.102,35.25,...,802.179,0.0,0.252,0.0,0.2124,29,19.0,24.0,13.0,82.0
482,1/1,08:02,482,34.8477,0.791282,126.37107,8.820,2.583,-5.017,35.34,...,802.268,0.0,0.200,0.0,0.2172,34,17.0,26.0,13.0,82.0
483,1/1,08:03,483,38.2096,0.697317,126.54226,8.820,2.546,-4.954,35.53,...,802.320,0.0,0.175,0.0,0.2176,38,14.0,30.0,13.0,82.0
484,1/1,08:04,484,40.9498,0.583570,126.71380,8.770,2.546,-4.954,35.65,...,802.376,0.0,0.187,0.0,0.2195,42,11.0,29.0,15.0,85.0
485,1/1,08:05,485,42.6432,0.534112,126.88571,8.740,2.525,-4.975,35.66,...,802.381,0.0,0.255,0.0,0.2175,40,10.0,26.0,15.0,86.0
486,1/1,08:06,486,43.5020,0.712150,127.05798,8.740,2.584,-4.906,35.87,...,802.419,0.0,0.205,0.0,0.2172,43,8.0,26.0,14.0,86.0
487,1/1,08:07,487,44.0582,0.682477,127.23062,8.730,2.496,-4.904,35.90,...,802.383,0.0,0.263,0.0,0.2163,42,7.0,27.0,14.0,88.0
488,1/1,08:08,488,44.7171,0.816005,127.40362,8.890,2.559,-5.041,35.10,...,802.299,0.0,0.376,0.0,0.2096,41,7.0,27.0,15.0,90.0
489,1/1,08:09,489,45.1827,1.612220,127.57698,9.120,2.711,-4.889,35.01,...,802.314,0.0,0.252,0.0,0.2129,40,7.0,28.0,17.0,91.0
490,1/1,08:10,490,44.9636,4.401470,127.75072,9.210,2.811,-4.889,34.80,...,802.302,0.0,0.257,0.0,0.2146,37,10.0,28.0,18.0,92.0
491,1/1,08:11,491,44.4127,12.650500,127.92483,9.250,2.803,-4.797,34.98,...,802.145,0.0,0.198,0.0,0.2186,35,11.0,28.0,21.0,93.0
492,1/1,08:12,492,41.2825,7.111610,128.09932,9.220,2.819,-4.681,35.40,...,802.169,0.0,0.159,0.0,0.2174,30,11.0,27.0,24.0,94.0
493,1/1,08:13,493,38.2460,2.903010,128.27418,9.160,2.765,-4.735,35.38,...,802.067,0.0,0.263,0.0,0.2101,29,12.0,25.0,23.0,93.0
494,1/1,08:14,494,35.8937,1.033610,128.44942,9.230,2.851,-4.839,34.90,...,802.043,0.0,0.272,0.0,0.2044,26,13.0,22.0,28.0,93.0
495,1/1,08:15,495,34.1675,0.544008,128.62504,9.320,2.838,-4.762,34.92,...,802.072,0.0,0.212,0.0,0.2058,25,13.0,19.0,34.0,94.0
496,1/1,08:16,496,32.9051,0.351133,128.80104,9.330,2.923,-4.767,34.88,...,802.043,0.0,0.245,0.0,0.2043,22,14.0,18.0,39.0,94.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
526556,12/31,15:56,956,53.6920,-0.197506,231.86720,2.768,-1.485,-7.785,42.32,...,812.385,0.0,2.759,0.0,0.2674,65,-1.0,-1.0,-1.0,-1.0
526557,12/31,15:57,957,52.3678,-0.192569,232.04185,2.767,-1.503,-7.903,41.89,...,812.417,0.0,2.749,0.0,0.2668,68,-1.0,-1.0,-1.0,-1.0
526558,12/31,15:58,958,50.4295,-0.222194,232.21612,2.768,-1.453,-7.753,42.44,...,812.436,0.0,2.734,0.0,0.2661,68,-1.0,-1.0,-1.0,-1.0
526559,12/31,15:59,959,48.0235,-0.237007,232.39003,2.745,-1.453,-7.853,42.14,...,812.452,0.0,2.744,0.0,0.2639,72,-1.0,-1.0,-1.0,-1.0
526560,12/31,16:00,960,45.6696,-0.237007,232.56356,2.718,-1.533,-8.033,41.56,...,812.477,0.0,2.730,0.0,0.2621,70,-1.0,-1.0,-1.0,-1.0
526561,12/31,16:01,961,43.4786,-0.177756,232.73672,2.680,-1.582,-7.982,41.86,...,812.496,0.0,2.729,0.0,0.2606,70,-1.0,-1.0,-1.0,-1.0
526562,12/31,16:02,962,41.0686,-0.158005,232.90952,2.640,-1.620,-8.020,41.84,...,812.514,0.0,2.728,0.0,0.2596,71,-1.0,-1.0,-1.0,-1.0
526563,12/31,16:03,963,38.7925,-0.128379,233.08195,2.589,-1.547,-7.847,42.63,...,812.531,0.0,2.720,0.0,0.2590,67,-1.0,-1.0,-1.0,-1.0
526564,12/31,16:04,964,37.0984,-0.128380,233.25402,2.551,-1.629,-8.029,42.07,...,812.544,0.0,2.764,0.0,0.2579,59,-1.0,-1.0,-1.0,-1.0
526565,12/31,16:05,965,35.9395,-0.103691,233.42573,2.529,-1.678,-8.178,41.59,...,812.559,0.0,2.779,0.0,0.2580,57,-1.0,-1.0,-1.0,-1.0
526566,12/31,16:06,966,34.8672,-0.098754,233.59708,2.530,-1.646,-7.946,42.44,...,812.576,0.0,2.738,0.0,0.2571,55,-1.0,-1.0,-1.0,-1.0
526567,12/31,16:07,967,33.5320,-0.079003,233.76808,2.528,-1.693,-8.193,41.54,...,812.580,0.0,2.754,0.0,0.2563,50,-1.0,-1.0,-1.0,-1.0
526568,12/31,16:08,968,31.8712,-0.093816,233.93871,2.527,-1.661,-8.161,41.66,...,812.609,0.0,2.759,0.0,0.2558,48,-1.0,-1.0,-1.0,-1.0
526569,12/31,16:09,969,30.3439,-0.044439,234.10900,2.528,-1.665,-8.165,41.64,...,812.616,0.0,2.714,0.0,0.2553,46,-1.0,-1.0,-1.0,-1.0
526570,12/31,16:10,970,29.0182,-0.074066,234.27893,2.524,-1.695,-8.095,41.91,...,812.625,0.0,2.745,0.0,0.2545,43,-1.0,-1.0,-1.0,-1.0
526571,12/31,16:11,971,27.5984,-0.093817,234.44852,2.509,-1.682,-8.082,42.00,...,812.648,0.0,2.748,0.0,0.2530,38,-1.0,-1.0,-1.0,-1.0
526572,12/31,16:12,972,26.0765,-0.093817,234.61776,2.494,-1.627,-8.027,42.25,...,812.647,0.0,2.681,0.0,0.2513,31,-1.0,-1.0,-1.0,-1.0
526573,12/31,16:13,973,24.5742,-0.118505,234.78666,2.482,-1.624,-7.924,42.67,...,812.655,0.0,2.689,0.0,0.2502,26,-1.0,-1.0,-1.0,-1.0
526574,12/31,16:14,974,23.3032,-0.158006,234.95521,2.458,-1.657,-7.957,42.62,...,812.656,0.0,2.695,0.0,0.2488,22,-1.0,-1.0,-1.0,-1.0
526575,12/31,16:15,975,22.1733,-0.158006,235.12342,2.430,-1.706,-8.006,42.52,...,812.655,0.0,2.696,0.0,0.2464,18,-1.0,-1.0,-1.0,-1.0
526576,12/31,16:16,976,21.0950,-0.138255,235.29130,2.412,-1.673,-7.973,42.70,...,812.654,0.0,2.685,0.0,0.2448,16,-1.0,-1.0,-1.0,-1.0
526577,12/31,16:17,977,19.8870,-0.172820,235.45883,2.391,-1.749,-8.049,42.48,...,812.654,0.0,2.680,0.0,0.2435,14,-1.0,-1.0,-1.0,-1.0
526578,12/31,16:18,978,18.7224,-0.212322,235.62604,2.371,-1.749,-8.049,42.54,...,812.647,0.0,2.665,0.0,0.2445,11,-1.0,-1.0,-1.0,-1.0
526579,12/31,16:19,979,17.9670,-0.227135,235.79291,2.350,-1.660,-7.660,44.08,...,812.635,0.0,2.649,0.0,0.2453,11,-1.0,-1.0,-1.0,-1.0
526580,12/31,16:20,980,17.4949,-0.241948,235.95945,2.303,-1.661,-7.561,44.61,...,812.638,0.0,2.630,0.0,0.2455,11,-1.0,-1.0,-1.0,-1.0
526581,12/31,16:21,981,17.0978,-0.222197,236.12566,2.272,-1.659,-7.659,44.33,...,812.643,0.0,2.658,0.0,0.2459,10,-1.0,-1.0,-1.0,-1.0
526582,12/31,16:22,982,16.5593,-0.202447,236.29155,2.245,-1.743,-7.743,44.09,...,812.653,0.0,2.674,0.0,0.2463,9,-1.0,-1.0,-1.0,-1.0
526583,12/31,16:23,983,15.6230,-0.197509,236.45711,2.235,-1.773,-7.973,43.24,...,812.664,0.0,2.696,0.0,0.2470,8,-1.0,-1.0,-1.0,-1.0
526584,12/31,16:24,984,14.5605,-0.202446,236.62235,2.245,-1.683,-7.683,44.32,...,812.675,0.0,2.654,0.0,0.2462,7,-1.0,-1.0,-1.0,-1.0
526585,12/31,16:25,985,13.7140,-0.222196,236.78727,2.226,-1.681,-7.581,44.78,...,812.695,0.0,2.653,0.0,0.2438,7,-1.0,-1.0,-1.0,-1.0

In [161]:
df6 = df4
df6 = df6.drop(['DATE (MM/DD)', 'MST'], axis=1)

In [151]:
df4.iloc[:, -4].values

array([20., 19., 17., ..., 47., 51., 54.])

In [174]:
X = df6.iloc[:, :-4].values
y1 = df6.iloc[:, -4].values
y2 = df6.iloc[:, -3].values
y3 = df6.iloc[:, -2].values
y4 = df6.iloc[:, -1].values

In [173]:
df6.head(2)

,time,CMP22,sNIP,Angle,dryBulbTemp,wetBulbTemp,dewPtTemp,RH,windSpeed,windDirection,pressure,rain,snowDepth,Moisture,Albedo,TCC,TCC_30min,TCC_60min,TCC_90min,TCC_120min
467,467,14.4935,0.079127,123.84491,6.933,1.403,-5.597,38.24,0.7,210.3,802.042,0.0,0.032,0.0,0.1951,6,20.0,13.0,17.0,46.0
468,468,16.5178,-0.034618,124.01096,6.793,1.294,-5.606,38.58,0.7,232.2,801.948,0.0,0.029,0.0,0.1867,8,19.0,15.0,14.0,52.0

In [175]:
from sklearn.model_selection import train_test_split
X_train, X_test, y1_train, y1_test = train_test_split(X, y1, test_size=0.2, random_state=0)

In [176]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y1_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [177]:
print(regressor.intercept_)

166.83341820569288

In [178]:
print(regressor.coef_)

[-3.26264859e-02  1.11544964e-02 -1.71739492e-02  8.82917534e-02
  6.75201713e-01 -9.08149003e-01  6.67005590e-02  1.14547035e-01
  8.75835196e-02 -8.42293285e-03 -1.83068947e-01 -1.00339569e-01
 -4.41290516e-04  1.15991116e+00 -2.88003114e+00  7.67248902e-01]

In [179]:
y1_pred = regressor.predict(X_test)

In [180]:
df_res1 = pd.DataFrame({'Actual': y1_test, 'Predicted': y1_pred})
df_res1

       Actual  Predicted
0        19.0  19.885659
1        64.0  87.873494
2         8.0  10.671792
3        99.0  95.427632
4        90.0  71.645173
5        83.0  40.374482
6        99.0  97.397867
7        18.0  18.575673
8        64.0  38.464863
9         6.0  10.216690
10       12.0  23.509769
11       97.0  97.461404
12       91.0  88.068611
13       94.0  92.437649
14       87.0  83.366279
15       98.0  93.200086
16       38.0  26.843973
17       86.0  93.353919
18       65.0  63.130151
19       57.0  81.484786
20       55.0  57.222209
21       14.0  18.032860
22       16.0  24.625495
23       23.0  39.581775
24       19.0  27.023864
25       32.0  39.324304
26       58.0  47.143613
27       17.0  15.582729
28       10.0   9.299087
29       30.0  34.334728
...       ...        ...
40296    23.0  57.024359
40297    97.0  93.002569
40298    42.0  35.139689
40299    88.0  80.626896
40300    10.0  15.558896
40301    51.0  62.533130
40302    61.0  70.697308
40303    12.0  18.240701
40304    91.0  90.360719
40305    96.0  88.546525
40306    94.0  64.162492
40307    74.0  46.572378
40308    99.0  94.519654
40309    71.0  61.565691
40310    29.0  35.241484
40311    18.0  47.648473
40312    18.0  29.693878
40313    69.0  33.488558
40314    61.0  31.834375
40315    48.0  60.127866
40316    80.0  56.943901
40317    26.0  16.234841
40318     5.0  23.063717
40319    71.0  80.570356
40320    13.0  12.423142
40321     5.0  12.470361
40322    24.0  35.001151
40323    98.0  97.597238
40324    15.0  20.216018
40325    14.0  15.845460

[40326 rows x 2 columns]

In [182]:
df_res1.mad()

Actual       33.247035
Predicted    30.065361
dtype: float64

In [184]:
df_res1.mean()

Actual       50.022219
Predicted    49.963805
dtype: float64

In [185]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(df_res1.Actual, df_res1.Predicted)

9.451738786184778

In [ ]:
df_train = df_train.rename(columns={'Global CMP22 (vent/cor) [W/m^2]':'CMP22', 'Direct sNIP [W/m^2]':'sNIP', 'Azimuth Angle [degrees]':'Angle', 'Tower Dry Bulb Temp [deg C]':'dryBulbTemp', 'Tower Wet Bulb Temp [deg C]':'wetBulbTemp', 'Tower Dew Point Temp [deg C]':'dewPtTemp', 'Tower RH [%]':'RH', 'Total Cloud Cover [%]':'TCC', 'Peak Wind Speed @ 6ft [m/s]':'windSpeed', 'Station Pressure [mBar]':'pressure', 'Precipitation (Accumulated) [mm]':'rain', 'Snow Depth [cm]':'snowDepth', 'Albedo (CMP11)':'Albedo','Avg Wind Direction @ 6ft [deg from N]':'windDirection'})

In [303]:
path = "D:\\Documents\\ML\\shell_dataset\\dataset\\test\\test\\"

# print(df6.columns)
X = df6.iloc[:, :-4].values
y1 = df6.iloc[:, -4].values
y2 = df6.iloc[:, -3].values
y3 = df6.iloc[:, -2].values
y4 = df6.iloc[:, -1].values
from sklearn.linear_model import LinearRegression
regressor1 = LinearRegression()
regressor2 = LinearRegression()
regressor3 = LinearRegression()
regressor4 = LinearRegression()


regressor1.fit(X, y1)
regressor2.fit(X, y2)
regressor3.fit(X, y3)
regressor4.fit(X, y4)

# print(X.shape)
# print(y1.shape)
min30=[]
min60=[]
min90=[]
min120=[]
columns = ['30_min_horizon', '60_min_horizon', '90_min_horizon','120_min_horizon']
indexList=[]
for i in range(1,301):
    fullpath=path+str(i)+'\\weather_data.csv'
    df_test = pd.read_csv(fullpath)
#     print(df_test.columns)
    df_test = df_test.rename(columns={'Time [Mins]':'time','Global CMP22 (vent/cor) [W/m^2]':'CMP22', 'Direct sNIP [W/m^2]':'sNIP', 'Azimuth Angle [degrees]':'Angle', 'Tower Dry Bulb Temp [deg C]':'dryBulbTemp', 'Tower Wet Bulb Temp [deg C]':'wetBulbTemp', 'Tower Dew Point Temp [deg C]':'dewPtTemp', 'Tower RH [%]':'RH', 'Total Cloud Cover [%]':'TCC', 'Peak Wind Speed @ 6ft [m/s]':'windSpeed', 'Station Pressure [mBar]':'pressure', 'Precipitation (Accumulated) [mm]':'rain', 'Snow Depth [cm]':'snowDepth', 'Albedo (CMP11)':'Albedo','Avg Wind Direction @ 6ft [deg from N]':'windDirection'})
    new_columnName = ['time', 'CMP22', 'sNIP', 'Angle', 'dryBulbTemp',
       'wetBulbTemp', 'dewPtTemp', 'RH', 'windSpeed', 'windDirection',
       'pressure', 'rain', 'snowDepth', 'Moisture', 'Albedo', 'TCC','TCC_30min', 'TCC_60min',
       'TCC_90min', 'TCC_120min']
    df_test = df_test.reindex(columns=new_columnName)
    df_test = df_test[df_test.TCC > -1]
#     print(df_test.columns)
#     s_test = df_test['MST']
#     arr=[]
#     print(df_test)
#     for index, val in s_test.items():
#         print(str(val).split(':')[0])
#         arr.append((int(str(val).split(':')[0])*60) + (int(str(val).split(':')[1])))
#     df_test_ = df_test.assign(time = arr)
#     new_columnName = ['DATE (MM/DD)', 'MST', 'time', 'CMP22', 'sNIP', 'Angle', 'dryBulbTemp',
#        'wetBulbTemp', 'dewPtTemp', 'RH', 'windSpeed', 'windDirection',
#        'pressure', 'rain', 'snowDepth', 'Moisture', 'Albedo', 'TCC', 'TCC_30min', 'TCC_60min','TCC_90min','TCC_120min']
#     df_test_ = df_test_.reindex(columns=new_columnName)
#     df_test_ = df_test_.drop(['DATE (MM/DD)', 'MST'], axis=1)
    X_test = df_test.iloc[:, :-4].values
#         y30_test = df_test_.iloc[:, -4].values
#         y60_test = df_test_.iloc[:, -3].values
#         y90_test = df_test_.iloc[:, -2].values
#         y120_test = df_test_.iloc[:, -1].values
#     Y_pred = 'y'+str(count)+'_pred'
#     print(X_test.shape)
    y30_pred = regressor1.predict(X_test)
    y60_pred = regressor2.predict(X_test)
    y90_pred = regressor3.predict(X_test)
    y120_pred = regressor4.predict(X_test)
    
#     print(y30_pred)
    for val in range(len(y30_pred)):
        y30_pred[val] = int(y30_pred[val]) if y30_pred[val]<=100 else 100
    for val in range(len(y60_pred)):
        y60_pred[val] = int(y60_pred[val]) if y60_pred[val]<=100 else 100
    for val in range(len(y90_pred)):
        y90_pred[val] = int(y90_pred[val]) if y90_pred[val]<=100 else 100
    for val in range(len(y120_pred)):
        y120_pred[val] = int(y120_pred[val]) if y120_pred[val]<=100 else 100
#     print(y30_pred)
#     y60_pred = regressor2.predict(X_test)
#     y90_pred = regressor3.predict(X_test)
#     y120_pred = regressor4.predict(X_test)

    df_res_test = pd.DataFrame({'30_min_horizon': y30_pred, '60_min_horizon':y60_pred, '90_min_horizon':y90_pred, '120_min_horizon':y120_pred})
    df_res_test1=df_res_test
    df_res_test1['30_min_horizon'] = df_res_test['30_min_horizon'].astype(int)
    df_res_test1['60_min_horizon'] = df_res_test['60_min_horizon'].astype(int)
    df_res_test1['90_min_horizon'] = df_res_test['90_min_horizon'].astype(int)
    df_res_test1['120_min_horizon'] = df_res_test['120_min_horizon'].astype(int)
    
#     print(df_res_test1.tail(1))
    
    min30.append(df_res_test1.iloc[-1]['30_min_horizon'])
    min60.append(df_res_test1.iloc[-1]['60_min_horizon'])
    min90.append(df_res_test1.iloc[-1]['90_min_horizon'])
    min120.append(df_res_test1.iloc[-1]['120_min_horizon'])
    
    indexList.append(i)
    
    
finalData = {'30_min_horizon':min30, '60_min_horizon':min60, '90_min_horizon':min90, '120_min_horizon':min120}
# index=indexList

finalDF = pd.DataFrame(finalData, index=indexList)
finalDF

     30_min_horizon  60_min_horizon  90_min_horizon  120_min_horizon
1               100             100             100              100
2                58              63              69               89
3               100             100             100              100
4                75              80              86              100
5                37              43              47               69
6                35              42              49               72
7                39              47              55               83
8                43              50              57               81
9                87              91              95              100
10               45              51              56               80
11              100             100             100              100
12              100             100             100              100
13               71              77              84              100
14               41              43              47               67
15               51              57              64               85
16               33              40              47               70
17              100             100             100              100
18               91              94              98              100
19               38              48              57               84
20              100             100             100              100
21               97              97              99              100
22               45              51              57               81
23              100             100             100              100
24               37              43              50               77
25               97              98             100              100
26              100             100             100              100
27               67              73              78              100
28               25              28              31               50
29               24              32              40               62
30              100             100             100              100
..              ...             ...             ...              ...
271              87              90              92              100
272              95              99             100              100
273             100             100             100              100
274              51              59              64               86
275              38              43              48               68
276              40              49              56               84
277              39              46              54               82
278              29              34              39               62
279              32              36              41               63
280              96             100             100              100
281              81              85              89              100
282              30              35              40               65
283              44              53              62               92
284              35              46              55               86
285              56              63              70               92
286             100             100             100              100
287              37              46              55               85
288              28              35              40               61
289              91              95              98              100
290              95              98             100              100
291              31              40              49               75
292              55              62              70               97
293             100             100             100              100
294              35              40              46               71
295              23              29              35               55
296              26              32              39               60
297              72              78              84              100
298              30              39              47               67
299              52              58              64               91
300              49              57              64               89

[300 rows x 4 columns]

In [204]:
df6.columns

Index(['time', 'CMP22', 'sNIP', 'Angle', 'dryBulbTemp', 'wetBulbTemp',
       'dewPtTemp', 'RH', 'windSpeed', 'windDirection', 'pressure', 'rain',
       'snowDepth', 'Moisture', 'Albedo', 'TCC', 'TCC_30min', 'TCC_60min',
       'TCC_90min', 'TCC_120min'],
      dtype='object')

In [270]:
df_res_test1=df_res_test
df_res_test1['30_min_horizon'] = df_res_test['30_min_horizon'].astype(int)
df_res_test1['30_min_horizon'].dtype
df_res_test1['30_min_horizon'].tail(1)

354    49
Name: 30_min_horizon, dtype: int32

In [305]:
finalDF.to_csv('D:\\Documents\\ML\\shell_dataset\\dataset\\submission.csv')